In [4]:
class Employee():
  ec = 0
  es = 0
  def __init__(self, name, family, department, salary = 0):
    self.name = name
    self.family = family
    self.salary = salary
    self.department = department
    Employee.ec += 1
    Employee.es += self.salary
  def avg_salary(self):
    return "The Average Salary is: $" + str(Employee.es / Employee.ec)
class Full_Time_Employee(Employee):
  fes = 0
  fec = 0
  def __init__(self, name, family, department,  salary):
    super().__init__(name, family, department)
    self.salary = salary
    Full_Time_Employee.fec += 1
    Full_Time_Employee.fes += self.salary
  def avg_salary(self):
      return "The Average Salary is: $" + str(Full_Time_Employee.fes / Full_Time_Employee.fec)
employee_1 = Employee("Sachin", "Beniwal", "Full Stack", 120000)
employee_2 = Employee("Chakradhar", "Jonanalagadda", "Salesforce", 140000)
employee_3 = Employee("Abhishek", "Gajula", "UI", 130000)
employee_4 = Employee("Phani", "Katta", "Devops", 100000)
full_employee_1 = Full_Time_Employee("Siddu", "Moosewala", "Techincal Architect in Java", 200000)
print("Total no. of employees in the company are: " + str(Employee.ec))
print("Total no. of full time employees in the company are: " + str(Full_Time_Employee.fec))
print()
print(employee_1.avg_salary())
print(full_employee_1.avg_salary())

Total no. of employees in the company are: 5
Total no. of full time employees in the company are: 1

The Average Salary is: $98000.0
The Average Salary is: $200000.0


In [3]:
import numpy as n
random_vector = n.arange(1, 21, dtype=float)
print(random_vector)
random_vector = random_vector.reshape(4,5)
print(random_vector)
random_vector = n.where(n.isin(random_vector, random_vector.max(axis=1)), 0, random_vector)
print(random_vector)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20.]
[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15.]
 [16. 17. 18. 19. 20.]]
[[ 1.  2.  3.  4.  0.]
 [ 6.  7.  8.  9.  0.]
 [11. 12. 13. 14.  0.]
 [16. 17. 18. 19.  0.]]
